import { NextResponse, type NextRequest } from "next/server";
import { SESSION_COOKIE } from "@/modules/identity/adapters/in/http/session-cookie";

// Public routes (no login required): the landing "/" and the login screen.
const PUBLIC_PATHS = new Set(["/", "/login"]);
// Where a signed-in user lands (the app itself).
const APP_HOME = "/procedimentos";

/**
 * Content-Security-Policy with a per-request nonce (OWASP A03 — injection).
 *
 * The nonce is what makes the policy worth having: without it the only way to
 * allow the inline scripts Next emits (the RSC payload, the theme script)
 * would be `'unsafe-inline'`, which lets any injected script run and turns the
 * header into decoration. Next reads the nonce from this header and stamps it
 * on every script it renders.
 *
 * Trade-off accepted knowingly: reading a request header makes the pages
 * dynamic, so the landing is no longer served as static HTML. A real CSP is
 * worth more than a few milliseconds of TTFB on one page.
 *
 * `img-src` is deliberately wide: material photos are URLs typed by the
 * clinic. They are validated as http/https by the `ImageUrl` value object, and
 * an image cannot execute — unlike a script, which only runs with the nonce.
 */
function contentSecurityPolicy(nonce: string): string {
  const dev = process.env.NODE_ENV !== "production";

  return [
    "default-src 'self'",
    // `strict-dynamic` lets the nonced bootstrap load the app chunks; the
    // http:/https: fallbacks are ignored by browsers that support it and keep
    // older ones from blocking everything. Dev needs eval for fast refresh.
    `script-src 'self' 'nonce-${nonce}' 'strict-dynamic' https: ${dev ? "'unsafe-eval'" : ""}`,
    // Styles are generated by Tailwind at build time, but Next injects a few
    // inline style tags; hashing them per build is not worth the coupling.
    "style-src 'self' 'unsafe-inline'",
    "img-src 'self' data: blob: https:",
    "font-src 'self' data:",
    `connect-src 'self'${dev ? " ws:" : ""}`,
    "object-src 'none'",
    "base-uri 'self'",
    "form-action 'self'",
    "frame-ancestors 'none'",
    ...(dev ? [] : ["upgrade-insecure-requests"]),
  ].join("; ");
}

/**
 * Protects the pages and sets the CSP.
 *
 * The middleware runs on the edge and cannot reach the database, so it only
 * checks that the session cookie is PRESENT. The real validation (valid,
 * unexpired token) happens in the API routes and in server components.
 */
export function middleware(req: NextRequest) {
  const { pathname } = req.nextUrl;

  // API routes handle their own authentication and answer 401 — redirecting a
  // fetch to the login HTML would break the client.
  if (pathname.startsWith("/api")) return NextResponse.next();

  const hasSession = req.cookies.has(SESSION_COOKIE);
  const isPublic = PUBLIC_PATHS.has(pathname);

  // No session on a protected route → login (keeping the destination).
  if (!hasSession && !isPublic) {
    const url = req.nextUrl.clone();
    url.pathname = "/login";
    url.search = `?next=${encodeURIComponent(pathname)}`;
    return NextResponse.redirect(url);
  }

  // A signed-in user needs neither login nor landing — straight to the app.
  if (hasSession && (pathname === "/login" || pathname === "/")) {
    const url = req.nextUrl.clone();
    url.pathname = APP_HOME;
    url.search = "";
    return NextResponse.redirect(url);
  }

  const nonce = crypto.randomUUID().replace(/-/g, "");
  const csp = contentSecurityPolicy(nonce);

  // The nonce travels to the server components through a request header, which
  // is how the inline theme script picks it up.
  const headers = new Headers(req.headers);
  headers.set("x-nonce", nonce);
  headers.set("content-security-policy", csp);

  const response = NextResponse.next({ request: { headers } });
  response.headers.set("content-security-policy", csp);
  return response;
}

// Static assets and the manifest stay out: a browser refuses resources served
// behind a redirect, and without a session the middleware would send them to
// /login.
export const config = {
  matcher: [
    "/((?!_next/static|_next/image|favicon.ico|robots.txt|sitemap.xml|manifest.webmanifest|sw.js|icon.svg|.*\\.(?:svg|png|jpg|jpeg|gif|webp|ico)$).*)",
  ],
};
